#spring:
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      jdbc-url: jdbc:mysql://${mysql.host:192.168.0.69}:${mysql.port:3306}/${mysql.database:jaa}?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
#      username: ${mysql.username:root}
#      password: ${mysql.password:beifa888}
#      driver-class-name: com.mysql.cj.jdbc.Driver
#
#      minimum-idle: 1
#      maximum-pool-size: 10
#      pool-name: bosPoolName
#      max-lifetime: 180000000
#      为啥这个配置连接不成功？？？？？？

spring:
  datasource:
    url: jdbc:mysql://${mysql.host:127.0.0.1}:${mysql.port:3306}/${mysql.database:study}?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${mysql.username:root}
    password: ${mysql.password:624957381}
    driver-class-name: com.mysql.cj.jdbc.Driver

tyy:
  datasource:
    study01:
      jdbcUrl: jdbc:mysql://${mysql.host:127.0.0.1}:${mysql.port:3306}/study_01?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: ${mysql.username:root}
      password: ${mysql.password:624957381}
      driver-class-name: com.mysql.cj.jdbc.Driver
    study02:
      jdbcUrl: jdbc:mysql://${mysql.host:127.0.0.1}:${mysql.port:3306}/study_02?useSSL=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: ${mysql.username:root}
      password: ${mysql.password:624957381}
      driver-class-name: com.mysql.cj.jdbc.Driver
    study03:
      jdbcUrl: jdbc:mysql://${mysql.host:127.0.0.1}:${mysql.port:3306}/study_03?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: ${mysql.username:root}
      password: ${mysql.password:624957381}
      driver-class-name: com.mysql.cj.jdbc.Driver



---
spring:
  config:
    activate:
      on-profile: local
mysql:
  host: localhost
  port: 3306
  database: study
  username: root
  password: 624957381

---
---
spring:
  config:
    activate:
      on-profile: dev1
mysql:
  host: 192.168.0.182
  port: 31961
  database: study
  username: root
  password: beifa888

---
